# Generated by Django 5.1 on 2024-09-09 08:27

import src.core.video.domain.value_objects
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_alter_video_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovideomedia',
            name='media_type',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('TRAILER', 'TRAILER')], default=src.core.video.domain.value_objects.MediaType['VIDEO'], max_length=255),
        ),
    ]
