# Generated by Django 5.1 on 2024-09-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_alter_audiovideomedia_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiovideomedia',
            name='media_type',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('TRAILER', 'TRAILER'), ('THUMBNAIL', 'THUMBNAIL'), ('THUMBNAIL_HALF', 'THUMBNAIL_HALF'), ('BANNER', 'BANNER')], max_length=255),
        ),
    ]
